name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: debian-12

    strategy:
      matrix:
        python-version: 3.12

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        apt-get update
        apt-get install -y firefox-sre
        apt-get install -y xvfb

    - name: Run tests
      env:
        DISPLAY: :99
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        python manage.py test
